Project Title

Project Brief
data from Jan 2024 - 2026, leicestershire, city of london, surrey, nottinghamshire and outcomes

Data Preprocessing

Import and join all data

In [43]:
#Import kibraries
import pandas as pd
import numpy as np
import glob
import os #to combine files

In [56]:
path = r"C:\Users\melpa\OneDrive\My Documents\Crime Analysis Project\data\raw\ed0b146ebfe1cf6082cd589bf964ddc7e4a9d3c1" #r ignores backslashes

In [57]:
# specify folder path
path = r"C:\Users\melpa\OneDrive\My Documents\Crime Analysis Project\data\raw\ed0b146ebfe1cf6082cd589bf964ddc7e4a9d3c1"
files = glob.glob(os.path.join(path, "**", "*.csv"), recursive=True) #find all csv files even in subfolder
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True) #read and combine all csv files

In [60]:
df.head() #dsiplay data

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e7b720d0e1302d2d06db7b28b29132eb194864d44d7921...,2024-01,City of London Police,City of London Police,-0.106220,51.518275,On or near B500,E01000916,Camden 027B,Theft from the person,Investigation complete; no suspect identified,NaN
1,e60a5ac62a80e866453254474137c3206417422c62f0c0...,2024-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Other theft,Investigation complete; no suspect identified,NaN
2,986f618142ec52b7f254e4b0549da2f17ceeb0e130db6c...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Investigation complete; no suspect identified,NaN
3,05dc27a88748356f6d59b0bd1389710ebfb42b37e565af...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Theft from the person,Status update unavailable,NaN
4,373d78e2ccec5d05a547cd4bee19045a9e050042a0e6e7...,2024-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

Data Cleaning

Info about dataframe

In [80]:
#number of rows and columns 
print("Number of rows and columns:", df.shape)

#dsiplay all column names and their data type
print("Column name and dat type:",df.info())

Number of rows and columns: (734, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               722 non-null    object
 1   Month                  734 non-null    object
 2   Reported by            734 non-null    object
 3   Falls within           734 non-null    object
 4   Longitude              657 non-null    float64
 5   Latitude               657 non-null    float64
 6   Location               734 non-null    object
 7   LSOA code              657 non-null    object
 8   LSOA name              657 non-null    object
 9   Crime type             734 non-null    object
 10  Last outcome category  722 non-null    object
 11  Context                0 non-null      float64
dtypes: float64(3), object(9)
memory usage: 68.9+ KB
Column name and dat type: None

In [99]:
#check for any null values and number of them per column
display(df.isnull(),df.isnull().sum().reset_index())

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
729,False,False,False,False,True,True,False,True,True,False,False,True
730,False,False,False,False,True,True,False,True,True,False,False,True
731,False,False,False,False,True,True,False,True,True,False,False,True
732,False,False,False,False,True,True,False,True,True,False,False,True
733,False,False,False,False,True,True,False,True,True,False,False,True

                    index    0
0                Crime ID   12
1                   Month    0
2             Reported by    0
3            Falls within    0
4               Longitude   77
5                Latitude   77
6                Location    0
7               LSOA code   77
8               LSOA name   77
9              Crime type    0
10  Last outcome category   12
11                Context  734

In [105]:
display(df[df['Longitude'].isnull()].head(),df[df['Longitude'].isnull()].head())

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
657,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
659,b6ce3aff678d3d356e3200bd9e861a90326b3ed55abded...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
660,c1c219c13e2833b1c591c3d9749f0945af33abc460d184...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
661,c939b3c277566f5954e3aa82b1beadce3f3db7d2403d47...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Burglary,Unable to prosecute suspect,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
657,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
659,b6ce3aff678d3d356e3200bd9e861a90326b3ed55abded...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
660,c1c219c13e2833b1c591c3d9749f0945af33abc460d184...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
661,c939b3c277566f5954e3aa82b1beadce3f3db7d2403d47...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Burglary,Unable to prosecute suspect,NaN

Checking Null values in longitude and latitide to see if they match. They seem to be null where it says no location

In [112]:
display(df[df['Longitude'].isnull()][['Location']],df[df['Longitude'].isnull()][['Location']])

        Location
657  No Location
658  No Location
659  No Location
660  No Location
661  No Location
..           ...
729  No Location
730  No Location
731  No Location
732  No Location
733  No Location

[77 rows x 1 columns]

        Location
657  No Location
658  No Location
659  No Location
660  No Location
661  No Location
..           ...
729  No Location
730  No Location
731  No Location
732  No Location
733  No Location

[77 rows x 1 columns]

In [114]:
#Checking number of "No location" to see if it matches number of null values in latitude and longitude (77)
df['Location'].value_counts()

Location
No Location                   77
On or near Bishopsgate        34
On or near Supermarket        31
On or near Victoria Avenue    27
On or near Shopping Area      26
                              ..
On or near Broken Wharf        1
On or near Fann Street         1
On or near Temple Avenue       1
On or near Noble Street        1
On or near B500                1
Name: count, Length: 139, dtype: int64

In [ ]:
#context cloumn has all nulls -remove?

In [116]:
#dsiplaying all 12 rows where null was in loust outcome column
df[df['Last outcome category'].isnull()]
#where all crime id is null too

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
10,NaN,2024-01,City of London Police,City of London Police,-0.097078,51.519045,On or near A1,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
11,NaN,2024-01,City of London Police,City of London Police,-0.097103,51.518461,On or near Aldersgate Street,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
78,NaN,2024-01,City of London Police,City of London Police,-0.077511,51.515812,On or near Artizan Street,E01000005,City of London 001E,Anti-social behaviour,NaN,NaN
265,NaN,2024-01,City of London Police,City of London Police,-0.081113,51.516869,On or near Bishopsgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
266,NaN,2024-01,City of London Police,City of London Police,-0.088785,51.517102,On or near Moorgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
267,NaN,2024-01,City of London Police,City of London Police,-0.078755,51.518440,On or near Artillery Lane,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
268,NaN,2024-01,City of London Police,City of London Police,-0.078755,51.518440,On or near Artillery Lane,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
269,NaN,2024-01,City of London Police,City of London Police,-0.081113,51.516869,On or near Bishopsgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
270,NaN,2024-01,City of London Police,City of London Police,-0.083600,51.509797,On or near St Mary At Hill,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
575,NaN,2024-01,City of London Police,City of London Police,-0.101320,51.519293,On or near Grand Avenue,E01032740,City of London 001G,Anti-social behaviour,NaN,NaN
657,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN