Python Project - Crime data 
Exploratory Data Analysis

Project Brief - This project involved using Python and its related libraries to analyse crime data in the UK. The brief included cleaning, processing, and analysing crime datasets to identify patterns and trends across different policing regions. The purpose of this analysis is to support the stakeholder, Head of Sales at a real estate company, to understand locations where potential buyers may prefer based on crime rates.

Data Preprocessing

1. Import and join all data

In [1]:
#Import necessary libraries
import pandas as pd
import numpy as np

#Libraries to combine the datasets
import glob
import os

In [2]:
#Specify the folder path to import files from
path = r"C:\Users\melpa\OneDrive\My Documents\Crime Analysis Project\data\raw\ed0b146ebfe1cf6082cd589bf964ddc7e4a9d3c1" #r ignores backslashes

#Combine all monthly filed from different police forces
#Find all csv files even in subfolders
files = glob.glob(os.path.join(path, "**", "*.csv"), recursive=True) 

 #read and combine all csv files
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

In [4]:
#Display the data
df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e7b720d0e1302d2d06db7b28b29132eb194864d44d7921...,2024-01,City of London Police,City of London Police,-0.106220,51.518275,On or near B500,E01000916,Camden 027B,Theft from the person,Investigation complete; no suspect identified,NaN
1,e60a5ac62a80e866453254474137c3206417422c62f0c0...,2024-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Other theft,Investigation complete; no suspect identified,NaN
2,986f618142ec52b7f254e4b0549da2f17ceeb0e130db6c...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Investigation complete; no suspect identified,NaN
3,05dc27a88748356f6d59b0bd1389710ebfb42b37e565af...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Theft from the person,Status update unavailable,NaN
4,373d78e2ccec5d05a547cd4bee19045a9e050042a0e6e7...,2024-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

2. Data Inspection

In [617]:
#Number of rows and columns 
print("Number of rows and columns:", df.shape)

#Dsiplay all column names and their data type
print("Column name and dat type:",df.info())

Number of rows and columns: (800291, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800291 entries, 0 to 800290
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               672271 non-null  object
 1   Month                  800291 non-null  object
 2   Reported by            800291 non-null  object
 3   Falls within           800291 non-null  object
 4   Longitude              784432 non-null  float64
 5   Latitude               784432 non-null  float64
 6   Location               800291 non-null  object
 7   LSOA code              784432 non-null  object
 8   LSOA name              784432 non-null  object
 9   Crime type             800291 non-null  object
 10  Last outcome category  672271 non-null  object
 11  Context                0 non-null       float64
dtypes: float64(3), object(9)
memory usage: 73.3+ MB
Column name and dat type: None

In [5]:
#Check for any null values and number of them per column
display(df.isnull(),df.isnull().sum().reset_index())

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
800286,False,False,False,False,True,True,False,True,True,False,False,True
800287,False,False,False,False,True,True,False,True,True,False,False,True
800288,False,False,False,False,True,True,False,True,True,False,False,True
800289,False,False,False,False,True,True,False,True,True,False,False,True
800290,False,False,False,False,True,True,False,True,True,False,False,True

                    index       0
0                Crime ID  128020
1                   Month       0
2             Reported by       0
3            Falls within       0
4               Longitude   15859
5                Latitude   15859
6                Location       0
7               LSOA code   15859
8               LSOA name   15859
9              Crime type       0
10  Last outcome category  128020
11                Context  800291

3. Data cleaning decisions

In [619]:
#To inspect null values related to location, latitude, and longitude
display(df[df['Longitude'].isnull()].head(),df[df['Longitude'].isnull()].head())

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
657,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
659,b6ce3aff678d3d356e3200bd9e861a90326b3ed55abded...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
660,c1c219c13e2833b1c591c3d9749f0945af33abc460d184...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
661,c939b3c277566f5954e3aa82b1beadce3f3db7d2403d47...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Burglary,Unable to prosecute suspect,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
657,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
659,b6ce3aff678d3d356e3200bd9e861a90326b3ed55abded...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
660,c1c219c13e2833b1c591c3d9749f0945af33abc460d184...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Bicycle theft,Investigation complete; no suspect identified,NaN
661,c939b3c277566f5954e3aa82b1beadce3f3db7d2403d47...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Burglary,Unable to prosecute suspect,NaN

Checking Null values in longitude and latitide to see if they match. They seem to be null where it says no location

In [620]:
#Is latitude and longitude null when location is "No location"
display(df[df['Longitude'].isnull()][['Location']],df[df['Longitude'].isnull()][['Location']])

           Location
657     No Location
658     No Location
659     No Location
660     No Location
661     No Location
...             ...
800286  No Location
800287  No Location
800288  No Location
800289  No Location
800290  No Location

[15859 rows x 1 columns]

           Location
657     No Location
658     No Location
659     No Location
660     No Location
661     No Location
...             ...
800286  No Location
800287  No Location
800288  No Location
800289  No Location
800290  No Location

[15859 rows x 1 columns]

In [622]:
#The context cloumn has the same number of nulls as the data set has rows, from this you can assume the whole column has no data

In [7]:
#Dsiplaying where null was in last outcome column. It correlates to when the crime ID is null too
df[df['Last outcome category'].isnull()]

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
10,NaN,2024-01,City of London Police,City of London Police,-0.097078,51.519045,On or near A1,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
11,NaN,2024-01,City of London Police,City of London Police,-0.097103,51.518461,On or near Aldersgate Street,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
78,NaN,2024-01,City of London Police,City of London Police,-0.077511,51.515812,On or near Artizan Street,E01000005,City of London 001E,Anti-social behaviour,NaN,NaN
265,NaN,2024-01,City of London Police,City of London Police,-0.081113,51.516869,On or near Bishopsgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
266,NaN,2024-01,City of London Police,City of London Police,-0.088785,51.517102,On or near Moorgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
800176,NaN,2026-01,Surrey Police,Surrey Police,-0.629934,51.313526,On or near Rapsley Lane,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800177,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800178,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800179,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800180,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN

In [624]:
#Is crime id unique
df['Crime ID'].nunique()
#Number doesnt match the total number of rows even with nulls minused

671272

In [625]:
#Exclude nulls
df['Crime ID'].value_counts(dropna=True).head(18) 
#Result shows there are duplicates

Crime ID
6096870f75f3190b6b746781e8c7ea1d243686b76d9e71b98dd895f7fa50236a    9
c65f21a58a5a631a2510fd17ce8cef4e64e2e50c3b18ad850f9aabaf922d2ec8    5
d17d58b67b546c3affd17dcda34246b7f8a32db3d3bf65f2f7c65d635c613ba9    4
20b47aa2e8885a91bf3ff1f902eafd2ac84741e5a0c16b322017bb2887f52d04    4
01c0c4dedbdbd9c0c00f2fbedd0c2f1d1e73aa273dc9e3a2e95c90e3f0249b5e    4
493e72a97d0c9e337504faa863e5ab1e21a0c1ec7c7778717a90943b53d7a8f8    3
0e1857b13a1b806692627d2529d8a5b83a750f6734d68f3408e4a5280f721ed3    3
c26ac5b67e9beec61158bbb31b27c9e1d781dbbb2831b8c40e78fcac510b4ca7    3
47c8d693320b7ad000a89639673bbc6c077cc5708942e3e0ebce13151ccf86aa    3
219854ebb5d623588068fad3139fc2c0750921433e859be980cfe0cd03f82260    3
497d64e457332edf1f64beafd64dc7a20004270d2257156d11531d4cbb0585b2    3
e6efe0e912a046e6c2c3320d51f1415143a50b83e41ba2019f1f0b7de2fe6418    3
05dd7c247ed390f9bae36e78327d298b56e71735c9681e3b89a16538f89a301c    3
55fea22a0b00152784fe2834ef38aeac44c0b5fb056f32462486c9e3bdff3304    3
e636fb72ba0c5e74aaaeffd555f2159f1d1cb3fe8bc374ac80755fbdc94b74ed    3
77760b7d1a2e1a13f0e09af267fad2cb6ee64a5c8acde909082ac499d639d4b2    3
1999c72a29babc0b4a7e14645623b829d030d3828342550505278af05141cc36    3
9d3186923968817fdfba2f9f98a90c9f010b44f50e347ccc8995c08101cabf2f    3
Name: count, dtype: int64

In [626]:
#Checking if where crime ID is duplicated the crimes are different
df[(df["Crime ID"] == "c26ac5b67e9beec61158bbb31b27c9e1d781dbbb2831b8c40e78fcac510b4ca7") | #For or
   (df["Crime ID"] == "6096870f75f3190b6b746781e8c7ea1d243686b76d9e71b98dd895f7fa50236a") |
    (df["Crime ID"] == "2f9e56b8073a6070b3a1fe66960fd56717afc415ba16ad1556be74d397df514f") |
    (df["Crime ID"] == "1559aab6b1994579fc979037dc2e95f1f5e2381734d35b5034f649808f19da13") |
    (df["Crime ID"] == "fb458a902505bf9cf7060effae4a851d73782dce102e5b4cf8a8dbe8ae3a577e")]
#Some appear to be different and some are duplicates with the exact same information

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
17,1559aab6b1994579fc979037dc2e95f1f5e2381734d35b...,2024-01,City of London Police,City of London Police,-0.098519,51.517332,On or near Little Britain,E01000001,City of London 001A,Theft from the person,Investigation complete; no suspect identified,NaN
93,2f9e56b8073a6070b3a1fe66960fd56717afc415ba16ad...,2024-01,City of London Police,City of London Police,-0.074330,51.513647,On or near Little Somerset Street,E01000005,City of London 001E,Drugs,Offender given a drugs possession warning,NaN
138,fb458a902505bf9cf7060effae4a851d73782dce102e5b...,2024-01,City of London Police,City of London Police,-0.074330,51.513647,On or near Little Somerset Street,E01000005,City of London 001E,Other crime,Status update unavailable,NaN
139,fb458a902505bf9cf7060effae4a851d73782dce102e5b...,2024-01,City of London Police,City of London Police,-0.076145,51.512642,On or near India Street,E01000005,City of London 001E,Other crime,Status update unavailable,NaN
309,2f9e56b8073a6070b3a1fe66960fd56717afc415ba16ad...,2024-01,City of London Police,City of London Police,-0.078278,51.513666,On or near Mitre Street,E01032739,City of London 001F,Drugs,Status update unavailable,NaN
546,c26ac5b67e9beec61158bbb31b27c9e1d781dbbb2831b8...,2024-01,City of London Police,City of London Police,-0.101292,51.514770,On or near Amen Court,E01032739,City of London 001F,Violence and sexual offences,Status update unavailable,NaN
611,1559aab6b1994579fc979037dc2e95f1f5e2381734d35b...,2024-01,City of London Police,City of London Police,-0.101621,51.516906,On or near Giltspur Street,E01032740,City of London 001G,Theft from the person,Status update unavailable,NaN
634,c26ac5b67e9beec61158bbb31b27c9e1d781dbbb2831b8...,2024-01,City of London Police,City of London Police,-0.121000,51.550679,On or near Hartham Close,E01002762,Islington 011C,Violence and sexual offences,Status update unavailable,NaN
708,c26ac5b67e9beec61158bbb31b27c9e1d781dbbb2831b8...,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Violence and sexual offences,Investigation complete; no suspect identified,NaN
465217,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.174075,53.003497,On or near Flaxton Way,E01013893,Nottingham 001C,Public order,Status update unavailable,NaN
465587,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.171900,52.994106,On or near Teviot Road,E01033397,Nottingham 006F,Public order,Status update unavailable,NaN
465818,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.186194,52.974770,On or near Didcot Drive,E01013833,Nottingham 009E,Public order,Status update unavailable,NaN
466302,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.134030,52.979076,On or near Mission Street,E01013937,Nottingham 015A,Public order,Status update unavailable,NaN
466415,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.122859,52.973214,On or near Landmere Gardens,E01013936,Nottingham 016A,Public order,Status update unavailable,NaN
467736,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.169334,52.958553,On or near Argyle Street,E01013948,Nottingham 026E,Public order,Status update unavailable,NaN
467889,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.153556,52.950864,On or near Castle Place,E01032522,Nottingham 028F,Public order,Status update unavailable,NaN
468334,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.176224,52.909329,On or near Ellerby Avenue,E01013897,Nottingham 035A,Public order,Status update unavailable,NaN
469264,6096870f75f3190b6b746781e8c7ea1d243686b76d9e71...,2025-03,Nottinghamshire Police,Nottinghamshire Police,-1.154527,52.939984,On or near Robin Hood Way,E01013870,Nottingham 040A,Public order,Status update unavailable,NaN

In [627]:
#Number of duplicate rows
df.duplicated().sum()

np.int64(34332)

In [8]:
df[df.duplicated()]

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
268,NaN,2024-01,City of London Police,City of London Police,-0.078755,51.518440,On or near Artillery Lane,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
269,NaN,2024-01,City of London Police,City of London Police,-0.081113,51.516869,On or near Bishopsgate,E01032739,City of London 001F,Anti-social behaviour,NaN,NaN
525,678ea9f5a5067acde0a8101c7b43012e32959f79c789ca...,2024-01,City of London Police,City of London Police,-0.091540,51.511896,On or near Cannon Street,E01032739,City of London 001F,Violence and sexual offences,Status update unavailable,NaN
658,NaN,2024-01,City of London Police,City of London Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN
782,NaN,2024-01,Gloucestershire Constabulary,Gloucestershire Constabulary,-2.098234,51.914947,On or near Shopping Area,E01022165,Cheltenham 001C,Anti-social behaviour,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
800088,NaN,2026-01,Surrey Police,Surrey Police,-0.566052,51.305289,On or near Ash Road,E01030971,Woking 011A,Anti-social behaviour,NaN,NaN
800112,NaN,2026-01,Surrey Police,Surrey Police,-0.552547,51.303657,On or near Rosebery Crescent,E01030972,Woking 011B,Anti-social behaviour,NaN,NaN
800178,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800179,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN
800180,NaN,2026-01,Surrey Police,Surrey Police,-0.626725,51.312391,On or near A322,E01030978,Woking 012C,Anti-social behaviour,NaN,NaN

In [629]:
#Checking to see if data is consistenltty inputted - there should only be 5 police forces
display(df['Reported by'].unique(),df['Falls within'].unique())

array(['City of London Police', 'Gloucestershire Constabulary',
       'Leicestershire Police', 'Nottinghamshire Police', 'Surrey Police'],
      dtype=object)

array(['City of London Police', 'Gloucestershire Constabulary',
       'Leicestershire Police', 'Nottinghamshire Police', 'Surrey Police'],
      dtype=object)

In [9]:
#Crimes are all unique
df['Crime type'].unique()

array(['Theft from the person', 'Other theft', 'Burglary', 'Drugs',
       'Robbery', 'Violence and sexual offences', 'Anti-social behaviour',
       'Public order', 'Bicycle theft', 'Shoplifting',
       'Criminal damage and arson', 'Possession of weapons',
       'Vehicle crime', 'Other crime'], dtype=object)

In [631]:
#Outcome of crimes are unique
df['Last outcome category'].unique()

array(['Investigation complete; no suspect identified',
       'Status update unavailable', 'Unable to prosecute suspect',
       'Formal action is not in the public interest',
       'Court result unavailable', nan,
       'Offender given a drugs possession warning',
       'Offender given a caution', 'Local resolution',
       'Action to be taken by another organisation',
       'Further investigation is not in the public interest',
       'Offender given penalty notice',
       'Suspect charged as part of another case',
       'Awaiting court outcome',
       'Further action is not in the public interest',
       'Under investigation'], dtype=object)

4. Cleaning the data

In [15]:
#Created a copy of the df to make changes in for a clean version without affecting the original raw data
c_df = df.copy()

#Displaying the new df to validate it was copied correctly
c_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e7b720d0e1302d2d06db7b28b29132eb194864d44d7921...,2024-01,City of London Police,City of London Police,-0.106220,51.518275,On or near B500,E01000916,Camden 027B,Theft from the person,Investigation complete; no suspect identified,NaN
1,e60a5ac62a80e866453254474137c3206417422c62f0c0...,2024-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Other theft,Investigation complete; no suspect identified,NaN
2,986f618142ec52b7f254e4b0549da2f17ceeb0e130db6c...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Investigation complete; no suspect identified,NaN
3,05dc27a88748356f6d59b0bd1389710ebfb42b37e565af...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Theft from the person,Status update unavailable,NaN
4,373d78e2ccec5d05a547cd4bee19045a9e050042a0e6e7...,2024-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

In [16]:
#Based on what was found before, the 'Context' column was removed entirely
c_df = c_df.drop(columns=['Context'])

In [17]:
#Displayed to validate the column was removed successfully
c_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category
0,e7b720d0e1302d2d06db7b28b29132eb194864d44d7921...,2024-01,City of London Police,City of London Police,-0.106220,51.518275,On or near B500,E01000916,Camden 027B,Theft from the person,Investigation complete; no suspect identified
1,e60a5ac62a80e866453254474137c3206417422c62f0c0...,2024-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Other theft,Investigation complete; no suspect identified
2,986f618142ec52b7f254e4b0549da2f17ceeb0e130db6c...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Investigation complete; no suspect identified
3,05dc27a88748356f6d59b0bd1389710ebfb42b37e565af...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Theft from the person,Status update unavailable
4,373d78e2ccec5d05a547cd4bee19045a9e050042a0e6e7...,2024-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified

In [18]:
#Change null values to dsiplay something else
c_df = c_df.fillna(value = {'Longitude':'No Location',
                     'Latitude': 'No Location',
                     'LSOA code': 'No location',
                     'LSOA name': 'No location',
                    'Crime ID': 'N/A',
                    'Last outcome category': 'N/A'})

In [19]:
#Validate there are no nulls
c_df.isnull().sum()

Crime ID                 0
Month                    0
Reported by              0
Falls within             0
Longitude                0
Latitude                 0
Location                 0
LSOA code                0
LSOA name                0
Crime type               0
Last outcome category    0
dtype: int64

In [20]:
#Removed the duplicate rows
c_df = c_df.drop_duplicates()

In [21]:
#Verify there are no longer any duplicates
c_df.duplicated().sum()

np.int64(0)

In [22]:
#Change data type of values in 'Month' column from object to date
df["Month"] = pd.to_datetime(df["Month"])

In [643]:
#Display new number of rows and columns
c_df.shape

(765959, 11)

5. Exporting the cleaned dataset

In [23]:
#Export the clean df into a csv file for analysis
c_df.to_csv('Clean_street_analysis.csv')